### ISSUE TITLE
请问什么时候可以公布代码呢？很期待

### ISSUE THREAD

**Issue by YoungofNUAA** [wyf0912/SinSR#1]
我们团队在做老港片修复，不知道模型在这个领域效果怎么样，很期待

**Comment by YunjinChen** [comment]
+1

**Comment by wyf0912** [comment]
Thanks for your interest!
I will organize the code recently and release the code soon (maybe in a month).

**Comment by Guaishou74851** [comment]
+1

**Comment by ccccccccccy22** [comment]
+1

**Comment by pvtoan** [comment]
Hi, 

Thank you for your interesting work!

Could I please know when you will release your source code?

**Comment by wyf0912** [comment]
Thanks for your interest and waiting!

All the code and pre-trained models are released~!
