### ISSUE TITLE
Why your traindata directory includes 'ffhq256'?

### ISSUE THREAD

**Issue by ssam2s** [wyf0912/SinSR#11]
I'm reproducting your training experiments. I can't find your mention about ffhq256 datasets in paper, but your traindata directory includes ffhq256. Should i prepare this dataset to reproduct your training?

**Comment by wyf0912** [comment]
We follow the training paradigm of ResShift for a fair comparison, which mainly uses imagenet as the training data and involves a small amount of face data from FFHQ.

In fact, we found our method can get convergence very fast so I guess whether including FFHQ256 is not very important. However, we do not have a try and you may include it to achieve a similar result.

**Comment by ssam2s** [comment]
Thanks for your answering !

In the ResShift repository, it seems that they used 256x256 cropped imagenet (not original imagenet). Is your paper requires original imagnet? or 256x256 imagenet like ResShift?

Also, when i execute your main_distill.py, it prints there are 38 images in val data set. Where did this come from?

**Comment by wyf0912** [comment]
The training data are exactly the same as ResShift.

If I remember correctly 38 val images are from "/testdata/RealSet128/"

**Comment by ssam2s** [comment]
Thank you for your answer. 

I'll close this issue :)

**Comment by prokaryote-hgy** [comment]
@ssam2s Hi, where did you see that ResShift used cropped images instead of the complete ones?

> Thanks for your answering !
> 
> In the ResShift repository, it seems that they used 256x256 cropped imagenet (not original imagenet). Is your paper requires original imagnet? or 256x256 imagenet like ResShift?
> 
> Also, when i execute your main_distill.py, it prints there are 38 images in val data set. Where did this come from?
