### ISSUE TITLE
the link of SinSR_v1.pth is 404

### ISSUE THREAD

**Issue by ningbende** [wyf0912/SinSR#12]
Thanks for your work. I want to test the model, but link of SinSR_v1.pth is 404.
would you please upload again ?
Downloading: "https://github.com/zsyOAOA/ResShift/releases/download/v2.0/SinSR_v1.pth" to SinSR/weights/SinSR_v1.pth

urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by wyf0912** [comment]
Could you try this link, i.e., https://github.com/wyf0912/SinSR/releases/download/v1.0/SinSR_v1.pth


![image](https://github.com/wyf0912/SinSR/assets/26561397/920f0cd6-11d1-4eeb-a1b8-d592926980b4)

**Comment by ningbende** [comment]
It works. Thanks so much,  the fast reply!

**Comment by ningbende** [comment]
It works. Thanks so much for the prompt response!
