### ISSUE TITLE
SinSR checkpoint file : not found

### ISSUE THREAD

**Issue by bukdohee** [wyf0912/SinSR#17]
I am unable to download the model from "https://github.com/zsyOAOA/ResShift/releases/download/v2.0/SinSR_v1.pth".

And I couldn't find it in "https://github.com/zsyOAOA/ResShift/releases" either. Where can I find the pretrained model?

**Comment by wyf0912** [comment]
Please find the checkpoint here

https://github.com/wyf0912/SinSR/releases/tag/v1.0

**Comment by Jamie725** [comment]
Thanks for the model weights sharing!
