### ISSUE TITLE
cannot run with "--scale 2"

### ISSUE THREAD

**Issue by LLLLLrf** [wyf0912/SinSR#18]
RuntimeError: Given groups=1, weight of size [160, 6, 3, 3], expected input[1, 15, 128, 160] to have 6 channels, but got 15 channels instead

**Comment by wyf0912** [comment]
Sorry, “--scale 2” is not implemented. 

Intuitively, 2x upsampling may not be able to reflect the advantages of generative models. However, if necessary, you can also try to modify the code to achieve

**Comment by ManuBN786** [comment]
--scale 1 is also not  working for 1X SR results.

So for 1X we need to train the model by ourselves ?

**Comment by jiaxiangc** [comment]
> Sorry, “--scale 2” is not implemented.
> 
> Intuitively, 2x upsampling may not be able to reflect the advantages of generative models. However, if necessary, you can also try to modify the code to achieve

How to modify the code？

**Comment by zouiner** [comment]
@jiaxiangc do you know that now? Could you please share the way to me?
