### ISSUE TITLE
other diffusion SR model

### ISSUE THREAD

**Issue by Harper714** [wyf0912/SinSR#19]
Hi, nice work! 
I have one question after reading the paper. Actually, we can use any diffusion SR model like LDM-SR with ODE sampler to get the training pair, and you chose ResShift just because the fewer sampling steps, am I right?

**Comment by wyf0912** [comment]
Yes. Originally, we thought the training might be slow so we used ResShift to speed up the training.

In fact, we find the training is very fast if w/o cycle consistency loss. It can converge in thousands of iterations. If you are interested, you can try to distill other SR models.
