### ISSUE TITLE
Waiting for code release

### ISSUE THREAD

**Issue by Guaishou74851** [wyf0912/SinSR#2]
A very interesting work. I can not wait to see and run the code to produce SR results using one step. :)

**Comment by pvtoan** [comment]
Hi,

Thank you so much for your valuable contributions!

I'm looking forward to seeing your release codes.

**Comment by wyf0912** [comment]
Thanks for your interest and waiting!

All the code and pre-trained models are released~!

**Comment by pvtoan** [comment]
Hi, 

Thank you so much!

Btw, could I know more about the pre-trained models including SinSR_v1.pth and SinSR_v2.pth, what are the differences between them?

**Comment by wyf0912** [comment]
> Hi,
> 
> Thank you so much!
> 
> Btw, could I know more about the pre-trained models including SinSR_v1.pth and SinSR_v2.pth, what are the differences between them?

Similar to ResShift, ```SinSR_v2.pth``` is an early-stop version of ```SinSR_v2.pth```, which has better MUSIQ and CLIPIQA while lower PSNR.

**Comment by pvtoan** [comment]
Thank you
