### ISSUE TITLE
Problems on reproducing the results in the paper

### ISSUE THREAD

**Issue by LiuZihang-star** [wyf0912/SinSR#22]
![微信图片_20240902161939](https://github.com/user-attachments/assets/95c91ceb-09cf-434f-b0ee-ae3745226c19)
作者你好，我在autodl上用RTX3090运行得到的表格1的结果与论文中稍有差异，请问如何解决？

**Comment by wyf0912** [comment]
<img width="987" alt="image" src="https://github.com/user-attachments/assets/4dd211ad-1b6f-4c6e-a1f3-6d6a6b059c22">

The results you obtained are slightly higher than that in our paper. I think it's acceptable due the randomness.

**Comment by liu979** [comment]
Thanks for your help
