### ISSUE TITLE
All configurations are according to yours, and the training data is also according to yours, but why is it stuck during training?I would be very grateful if you could reply me when you have time.

### ISSUE THREAD

**Issue by Yingchi1998** [wyf0912/SinSR#23]
![11](https://github.com/user-attachments/assets/ff978785-3aeb-405d-9634-a267494411fe)
All configurations are according to yours, and the training data is also according to yours, but why is it stuck during training?
I would be very grateful if you could reply me when you have time.

**Comment by Yingchi1998** [comment]
I saw it wrong

**Comment by ManuBN786** [comment]
How did you fix this ?

**Comment by ChenQiaoling00** [comment]
How did you fix this ?
