### ISSUE TITLE
Supplementary material

### ISSUE THREAD

**Issue by BadeiAlrahel** [wyf0912/SinSR#3]
Hello, great work ! I already implemented the paper and trained SinSR on my data, the results are not as good as the ones in the paper, but I am trying to improve them ! I still have a question about the derivation of the k_t, m_t, and j_t for the ResShift deterministic sampling, where can I find the full derivation ? Did you publish it somewhere ?

Looking forward for the code release so I can compare your implementation and mine !

**Comment by wyf0912** [comment]
[Supplementary.pdf](https://github.com/wyf0912/SinSR/files/14535217/single_step_SR_CVPR.39._compressed.pdf)
