### ISSUE TITLE
App.py example file missing

### ISSUE THREAD

**Issue by Phhofm** [wyf0912/SinSR#6]
Hey, thank you for your work :)

I just wanted to hint towards something real quick and also for others to see
When running 'python app.py' in the terminal,
The error message "FileNotFoundError: [Errno 2] No such file or directory: './testdata/RealSet65/bears.jpg'" will appear. Because the referenced example image file does not exist in your repository.

To remedy this and to be able to run the web demo, one needs to delete [line 135 in the app.py file](https://github.com/wyf0912/SinSR/blob/f5552bba522613de58af1d452802b8a2b2721a5b/app.py#L135).
So ['./testdata/RealSet65/bears.jpg', True, "SinSR", 12345], need to be deleted, since the image file is non-existent, otherwise the demo will not be able to start. After deleting this line, it will work :)

**Comment by wyf0912** [comment]
Thanks for pointing that out.
I found that I missed uploading some test data in jpg format previously and I have just fixed the issue.
