### ISSUE TITLE
Question about reproduction.

### ISSUE THREAD

**Issue by jiaxiangc** [wyf0912/SinSR#9]
Does your inverse loss (in paper) decrease？ I try to reproduce it, but it always be 1.0.

**Comment by wyf0912** [comment]
The inverse loss remains unchanged is abnormal.

Did you make any changes to the code and could you post the training log?

The inverse loss can decrease normally when I trained the models.

**Comment by wyf0912** [comment]
Besides, you can check the inverse loss of the provided checkpoints. I think the inverse loss in checkpoints shall be much smaller than 1.
